### ISSUE TITLE
Connection gets dropped

### ISSUE THREAD

**Issue by ethaniel** [wildfoundry/dataplicity-porthole-releases-osx#25]
When I run this command through the porthole SSH connection:
```
sudo apt -y install php7.3-cli php7.3-curl monit gstreamer1.0-tools gstreamer1.0-plugins-bad gstreamer1.0-alsa screen miniupnpc telnet
```

It runs for a few seconds and then my SSH connection gets dropped. I have to relogin, but then my command is running in the background and I can't see the output anymore.

**Comment by ernovout** [comment]
I've got the same problem. My iTerm session halts after a while to an error like this:

```
Bad packet length 2157630882.%
ssh_dispatch_run_fatal: Connection to 127.0.0.1 port 10020: Connection corrupted
```

And if transferring files e.g. with Cyberduck, I get this: 
```
2021-10-13 10:21:36,571 [reader] ERROR net.schmizz.sshj.transport.Decoder - Error decoding packet (invalid length) 98 b7 65 94 b5 01 9f b6 ff 2d 12 a3
2021-10-13 10:21:36,571 [reader] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - invalid packet length: 476985571
net.schmizz.sshj.transport.TransportException: [PROTOCOL_ERROR] invalid packet length: 476985571
	at net.schmizz.sshj.transport.Decoder.checkPacketLength(Decoder.java:185)
	at net.schmizz.sshj.transport.Decoder.decryptLength(Decoder.java:173)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:86)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:200)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:60)
```

So something weird going on with the packet length, it seems. 

EDIT: ... Porthole on Windows doesn't do this and the connection works fine. So it seems the issue is specifically on Porthole for MacOS.

**Comment by PawelErnestLuczak** [comment]
@ernovout We have just released version 1.15 that should have this connection issue fixed.

**Comment by ernovout** [comment]
Thanks for a such a quick response 😊 It does work now 🎉
